spring:
  application:
    name: AI-Service
  data:
    mongodb:
      uri: mongodb://localhost:27017/ResumeBuilder
      database: ResumeBuilder

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8082


gemini:
  api:
    url: ${GEMINI_URL}
    key: ${GEMINI_KEY}